import { makeStyles } from '@material-ui/core/styles';

export default makeStyles((theme) => ({
  formContainer: {
    margin: '100px auto',
    width: '1000px',
    boxShadow:
      '0 5px 8px 0 rgba(0, 0, 0, 0.2), 0 7px 20px 0 rgba(0, 0, 0, 0.2)',
    position: 'relative',
    borderRadius: '10px',
    height: '610px',
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
  },
  closeBtn: {
    position: 'absolute',
    top: '2%',
    right: '3%',
    fontSize: '1.5rem',
    zIndex: 1,
    color: '#fff',
    cursor: 'pointer',
  },
  contentLeft: {
    backgroundColor: 'white',
    borderRadius: '10px 0 0 10px',
    position: 'relative',
  },
  formImg: {
    width: '60%',
    height: '50%',
    position: 'absolute',
    top: '55%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
  },
  formHeading: {
    color: '#330055',
    display: 'flex',
    justifyContent: 'center',
    fontSize: '3.5rem',
    marginTop: '5rem',
  },
  contentRight: {
    borderRadius: '0 10px 10px 0',
    position: 'relative',
    background: '#63CEDD',
  },
  form: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    width: '90%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  formTitle: {
    fontSize: '1.4rem',
    textAlign: 'start',
    width: '80%',
    marginBottom: '1rem',
    color: '#330055',
  },
  formInputs: {
    marginBottom: '0.5rem',
    width: '80%',
  },
  formInputsP: {
    fontSize: '0.8rem',
    marginTop: '0.5rem',
    color: '#f00e0e',
  },
  formLabel: {
    display: 'inline-block',
    fontSize: '0.9rem',
    marginBottom: '6px',
    color: '#330055',
  },
  formInputPlaceholder: {},
  formInput: {
    display: 'block',
    paddingLeft: '10px',
    outline: 'none',
    borderRadius: '2px',
    height: '40px',
    width: '100%',
    border: 'none',
    '&::placeholder': {
      color: '#595959',
      fontSize: '12px',
    },
  },
  formInputBtn: {
    width: '80%',
    height: '50px',
    marginTop: '10px',
    borderRadius: '2px',
    background: '#330055',
    outline: 'none',
    border: 'none',
    color: '#fff',
    fontSize: '1rem',
    cursor: 'pointer',
    transition: 'all 0.3s',
    '&:hover': {
      background: 'white',
      color: '#330055',
    },
  },
  formInputLogin: {
    fontSize: '0.8rem',
    marginTop: '10px',
    color: '#330055',
    width: '80%',
    textAlign: 'center',
  },
  formInputLoginLink: {
    textDecoration: 'none',
    color: 'blue',
    fontWeight: 600,
  },
  formSuccess: {
    textAlign: 'center',
    fontSize: '24px',
    marginTop: '80px',
    color: '#fff',
  },
  formImg2: {
    width: '60%',
    height: '60%',
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
  },
}));
